title: Plone Intranet
author: Cornelis G. A. Kolbach
baseurl: /
domain: demo.ploneintranet.net
media: /media
markdown: kramdown
permalink: /:title
# org_id: plone-intranet
org_id: rkz
# org_id: ikath
sass:
  style: :compressed
exclude: 
  - Gemfile
  - Gemfile.lock
  - config.codekit
  - config.rb
  - vendor
  - src/bower_components
  - node_modules
