title: Folio Intranet
author: Cornelis G. A. Kolbach
baseurl: /
domain: demo.ploneintranet.net
media: /media
markdown: kramdown
permalink: /:title
sass:
  style: :compressed
exclude: 
  - Gemfile
  - Gemfile.lock
  - config.codekit
  - config.rb
  - vendor
  - src/bower_components
  - node_modules
