title: Plone Intranet
author: Cornelis G. A. Kolbach
baseurl: /
domain: demo.ploneintranet.net
media: /media
markdown: kramdown
permalink: /:title
# org_id: plone-intranet
# colour_1: #efefef
# colour_1_contrast: #666
# colour_1_separation_line: "#eb5b4e"
org_id: rkz
colour_1: "#eb5b4e"
colour_1_contrast: "#fff"
colour_1_separation_line: "#fff"
sass:
  style: :compressed
exclude: 
  - Gemfile
  - Gemfile.lock
  - config.codekit
  - config.rb
  - vendor
  - src/bower_components
  - node_modules
