title: Patterns
author: Cornelis G. A. Kolbach
baseurl: /prototype/
media: /media
markdown: kramdown
permalink: /:title
sass:
  style: :compressed
exclude: 
  - Gemfile
  - Gemfile.lock
  - config.codekit
  - config.rb
