title: Patterns
author: Cornelis G. A. Kolbach
baseurl: http://demo.ploneintranet.net
domain: demo.ploneintranet.net
media: /media
markdown: kramdown
permalink: /:title
colour-1: #efefef
colour-1-contrast: #666
sass:
  style: :compressed
exclude: 
  - Gemfile
  - Gemfile.lock
  - config.codekit
  - config.rb
  - vendor
  - src/bower_components
  - node_modules
